name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
categories:
  - title: '🚀 Major changes'
    label: 'major'
  - title: '✨ Enhancements'
    label: 'minor'
  - title: '🐛 Bug fixes'
    label: 'patch'
  - title: '📖 Documentation'
    label: 'documentation'
template: |
  ## Changelog

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
